version: '3'

services:
  appointments:
    image: usmans58/appointments:9a1a9c1a498d421190d78642ffdb9a8a3ae929e2
    ports:
      - "7070:7070"
    networks:
      - mynetwork

  doctors:
    image: usmans58/doctors:9a1a9c1a498d421190d78642ffdb9a8a3ae929e2
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: usmans58/frontend:9a1a9c1a498d421190d78642ffdb9a8a3ae929e2
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: 192.168.18.48:9090
      APPOINTMENTS_SERVICE_URL: 192.168.18.48:7070
    networks:
      - mynetwork
  mysql:
      image: usmans58/db:1
      ports:
        - "3306:3306"
      environment:
       - .env
      networks:
        - mynetwork


networks:
  mynetwork:
