version: '3'

services:
  appointments:
    image: usmans58/appointments:500674880cc050ecb1968246da0050b1ca61e78e
    ports:
      - "7070:7070"
    networks:
      - mynetwork

  doctors:
    image: usmans58/doctors:500674880cc050ecb1968246da0050b1ca61e78e
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: usmans58/frontend:c935ed022e5f97bc2a43751df251d5b576f366efs
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: 192.168.18.48:9090
      APPOINTMENTS_SERVICE_URL: 192.168.18.48:7070
    networks:
      - mynetwork

# db:
#   image: mysql:latest
#   environment:
#     MYSQL_ROOT_PASSWORD: example_root_password
#     MYSQL_DATABASE: example_database
#     MYSQL_USER: example_user
#     MYSQL_PASSWORD: example_password
#   ports:
#     - "3306:3306"
#   networks:
#     - mynetwork

networks:
  mynetwork:
