version: '3'

services:
  appointments:
    image: usmans58/appointments:25496c80f52bc138cecc0efb3f46b02975fe77ed
    ports:
      - "7070:7070"
    networks:
      - mynetwork

  doctors:
    image: usmans58/doctors:b1a39bef9f8240d4b2d5a2a3cbeb508acae4a947
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: usmans58/frontend:96b5c80a544c9c20b2303a0c8c6c7312bd1cfedc
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: 192.168.18.48:9090
      APPOINTMENTS_SERVICE_URL: 192.168.18.48:7070
    networks:
      - mynetwork

# db:
#   image: mysql:latest
#   environment:
#     MYSQL_ROOT_PASSWORD: example_root_password
#     MYSQL_DATABASE: example_database
#     MYSQL_USER: example_user
#     MYSQL_PASSWORD: example_password
#   ports:
#     - "3306:3306"
#   networks:
#     - mynetwork

networks:
  mynetwork:
