version: '3'

services:
  appointments:
    image: usmans58/appointments:f9c2b9cda746bce49ccaf832cdaaaa97e24c591e
    ports:
      - "7070:7070"
    networks:
      - mynetwork

  doctors:
    image: usmans58/doctors:475f8a3f60d862179c00419d78df75224f89f543
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: usmans58/frontend:475f8a3f60d862179c00419d78df75224f89f543
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: 192.168.18.48:9090
      APPOINTMENTS_SERVICE_URL: 192.168.18.48:7070
    networks:
      - mynetwork
  mysql:
      image: usmans58/db:1
      ports:
        - "3306:3306"
      environment:
       - .env
      networks:
        - mynetwork


networks:
  mynetwork:
