version: '3'

services:
  appointments:
    image: usmans58/appointments:a58c4476d71b6d5833b9f5a9d3cd0b985036cb01
    ports:
      - "7070:7070"
    networks:
      - mynetwork

  doctors:
    image: usmans58/doctors:71ff308812cdfc50fcda523b47bd876edb233712
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: usmans58/frontend:a58c4476d71b6d5833b9f5a9d3cd0b985036cb01
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: 192.168.18.48:9090
      APPOINTMENTS_SERVICE_URL: 192.168.18.48:7070
    networks:
      - mynetwork
  mysql:
      image: usmans58/db:1
      ports:
        - "3306:3306"
      environment:
       - .env
      networks:
        - mynetwork


networks:
  mynetwork:
