version: '3'

services:
  appointments:
    image: usmans58/appointments:fe6e05561dbb1e37af64996851173a9fc012ef29c0c144db030e645d8513766d277407056aba664
    ports:
      - "7070:7070"
    networks:
      - mynetwork

  doctors:
    image: usmans58/doctors:fe6e05561dbb1e37af64996851173a9fc012ef29c0c144db030e645d8513766d277407056aba664
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: usmans58/frontend:fe6e05561dbb1e37af64996851173a9fc012ef29c0c144db030e645d8513766d277407056aba664
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: 192.168.18.48:9090
      APPOINTMENTS_SERVICE_URL: 192.168.18.48:7070
    networks:
      - mynetwork

# db:
#   image: mysql:latest
#   environment:
#     MYSQL_ROOT_PASSWORD: example_root_password
#     MYSQL_DATABASE: example_database
#     MYSQL_USER: example_user
#     MYSQL_PASSWORD: example_password
#   ports:
#     - "3306:3306"
#   networks:
#     - mynetwork

networks:
  mynetwork:
