
apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
type: Opaque
data:
  NAME: YWRtaW4=
  PASSWORD: YWRtaW4=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: usmans58/appointments:f9c2b9cda746bce49ccaf832cdaaaa97e24c591e
        ports:
        - containerPort: 7070
        env:
        - name: NAME
          valueFrom:
            secretKeyRef:
              name: appointment-secret
              key: NAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: appointment-secret
              key: PASSWORD
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 7070
        livenessProbe:
          httpGet:
            path: /
            port: 7070

---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
