name: Appointments Microservice CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build-appointments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Appointments microservice
        run: |
          cd appointments
          docker build -t usmans58/appointments:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push usmans58/appointments:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1

