name: Doctors Microservice CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - doctors/**
  push:
    branches:
      - main
    paths:
      - doctors/**

jobs:
  build-doctors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Doctors microservice
        run: |
          cd doctors
          DOCKER_BUILDKIT=1 docker build -t usmans58/doctors:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push usmans58/doctors:${{ github.sha }}

      - name: Update docker-compose file
        run: |
          # Replace entire existing image tag with the full commit SHA
          sed -i 's/usmans58\/doctors:[0-9a-f]\{40\}/usmans58\/doctors:${{ github.sha }}/' docker-compose.yaml

      - name: Commit and push changes
        if: github.event_name == 'push'
        run: |
          git config user.email "usmansiddiqui51@gmail.com"
          git config user.name "usmans58"
          git add docker-compose.yaml
          git commit -m "Update docker-compose with built image tag of doctors microservice"
          git config pull.rebase true
          git pull
          git push https://${{ secrets.DEVOPS_PROJECT }}@github.com/usmans58/Devops_Project.git HEAD:main

