name: Doctors Microservice CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-doctors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Doctors microservice
        run: |
          cd doctors
          docker build -t usmans58/doctors:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push usmans58/doctors:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
