name: Frontend Microservice CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Frontend microservice
        run: |
          cd frontend
          docker build -t usmans58/frontend:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push usmans58/frontend:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
