name: Frontend Microservice CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Frontend microservice
        run: |
          cd frontend
          docker build -t usmans58/frontend:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push usmans58/frontend:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
      - name: Update docker-compose file
        run: |
          sed -i "s/usmans58\/appointments:1/usmans58\/appointments:${{ github.sha }}/g" ../docker-compose.yaml

      - name: Commit and push changes
        if: github.event_name == 'push'
        run: |
          git config user.email "usmansiddiqui51@gmail.com"
          git config user.name "usmans58"
          git add ../docker-compose.yaml
          git commit -m "Update docker-compose with built image tag of frontend microservice"
          git push https://${{ secrets.DEVOPS_PROJECT }}@github.com/usmans58/Devops_Project.git HEAD:main
